import { catId } from '@/conf/canbanData'

interface Iobject {
    [key: string]: any
}

export const defaultDeal: Iobject = {
  'company.name': null,
  'deal.name': null,
  'deal.purpose': null,
  'deal.roof': null,
  'deal.size.l': null,
  'deal.size.w': null,
  'deal.size.h': null,
  'deal.material': null,
  'deal.region': null,
  'deal.city': null,
  'deal.price': null,
  'deal.priceParts.production': null,
  'deal.priceParts.delivery': null,
  'deal.priceParts.installation': null,
  'deal.adress': null,
  'deal.info': '',
  'deal.source': null,
  'stage.type': null,
  'stage.datetime': null,
  'responsible.id': null,
  'company.contacts': [],
  contacts: [],
  'deal.additions.windows': [],
  'deal.additions.doors': [],
  'deal.additions.gates': [],
  'deal.additions.cranes': [],
  catId,
  datetime: null,
  active: 1,
  status: 0,
}

export const dealItemNames: Iobject = {
  'company.name': 'Название компании',
  'deal.name': 'Название сделки',
  'deal.purpose': 'Тип здания',
  'deal.roof': 'Тип крыши',
  'deal.size.l': 'Длина здания',
  'deal.size.w': 'Ширина здания',
  'deal.size.h': 'Высота здания',
  'deal.material': 'Материал',
  'deal.region': 'Регион и город',
  'deal.city': 'Город поставки',
  'deal.price': 'Общая цена',
  'deal.priceParts.production': 'Цена производства',
  'deal.priceParts.delivery': 'Цена доставки',
  'deal.priceParts.installation': 'Цена монтажа',
  'deal.adress': 'Адрес',
  'deal.info': 'Дополнительная информация',
  'deal.source': 'Источник сделки',
  'stage.type': 'Стадия',
  'responsible.id': 'Ответственный',
  'company.contacts': 'Контакты компании',
  contacts: 'Контакты',
  'deal.additions.windows': 'Окна',
  'deal.additions.doors': 'Двери',
  'deal.additions.gates': 'Ворота',
  'deal.additions.cranes': 'Кран-балка',
  active: 'Активность сделки',
  status: 'Статус сделки',
}
