interface Iobject {
    [key: string]: any
}

export const canbanStages: Iobject = [
  { name: 'Первый контакт' },
  { name: 'Отправка КП' },
  { name: 'Переговоры' },
  { name: 'Принимают решение' },
  { name: 'Согласование договора' },
  { name: 'Оплата аванса' },
  { name: 'Исполнение' },
  { name: 'Окончательный расчет' },
]

export const reloadDatetimeInterval = 30

export const canbanDealleftDataScheme = {
  'company.name': {
    item: 'company.name',
    changeStage: [0, 1, 2, 3, 4],
    type: 'text',
    'min-length': 5,
    'max-length': 255,
    simbols: 'all',
    list: null,
    value: '',
  },
  'deal.name': {
    item: 'deal.name',
    changeStage: [0, 1, 2, 3, 4],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'dealNames',
    value: '',
  },
  'deal.purpose': {
    item: 'deal.purpose',
    changeStage: [0, 1, 2, 3, 4],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'purposes',
    value: '',
  },
  'deal.roof': {
    item: 'deal.roof',
    changeStage: [0, 1, 2, 3, 4],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'roofs',
    value: '',
  },
  'deal.size.l': {
    item: 'deal.size.l',
    changeStage: [0, 1, 2, 3, 4],
    type: 'tel',
    'min-value': 3,
    'max-value': 60,
    simbols: 'digits',
    list: null,
    value: '',
  },
  'deal.size.w': {
    item: 'deal.size.w',
    changeStage: [0, 1, 2, 3, 4],
    type: 'tel',
    'min-value': 3,
    'max-value': 60,
    simbols: 'digits',
    list: null,
    value: '',
  },
  'deal.size.h': {
    item: 'deal.size.h',
    changeStage: [0, 1, 2, 3, 4],
    type: 'tel',
    'min-value': 2,
    'max-value': 8,
    simbols: 'digits',
    list: null,
    value: '',
  },
  'deal.material': {
    item: 'deal.material',
    changeStage: [0, 1, 2, 3, 4],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'materials',
    value: '',
  },
  'deal.region': {
    item: 'deal.region',
    changeStage: [0, 1, 2, 3, 4],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'regions',
    value: '',
  },
  'deal.city': {
    item: 'city',
    changeStage: [0, 1, 2, 3, 4],
    type: 'text',
    'min-length': 3,
    'max-length': 255,
    simbols: 'all',
    list: null,
    value: '',
  },
  'deal.price': {
    item: 'deal.price',
    changeStage: [0, 1, 2, 3, 4],
    type: 'tel',
    'min-value': 1000,
    'max-value': 1000000000,
    simbols: 'digits',
    list: null,
    value: '',
  },
  'deal.priceParts.production': {
    item: 'deal.priceParts.production',
    changeStage: [0, 1, 2, 3, 4],
    type: 'tel',
    'min-value': 1000,
    'max-value': 1000000000,
    simbols: 'digits',
    list: null,
    value: '',
  },
  'deal.priceParts.delivery': {
    item: 'deal.priceParts.delivery',
    changeStage: [0, 1, 2, 3, 4],
    type: 'tel',
    'min-value': 1000,
    'max-value': 1000000000,
    simbols: 'digits',
    list: null,
    value: '',
  },
  'deal.priceParts.installation': {
    item: 'deal.priceParts.installation',
    changeStage: [0, 1, 2, 3, 4],
    type: 'tel',
    'min-value': 1000,
    'max-value': 1000000000,
    simbols: 'digits',
    list: null,
    value: '',
  },
  'deal.adress': {
    item: 'deal.adress',
    changeStage: [0, 1, 2, 3, 4, 5, 6, 7],
    type: 'text',
    'min-length': 3,
    'max-length': 255,
    simbols: 'all',
    list: null,
    value: '',
  },
  'deal.info': {
    item: 'deal.info',
    changeStage: [0, 1, 2, 3, 4, 5, 6, 7],
    type: 'text',
    'min-length': 3,
    'max-length': 255,
    simbols: 'all',
    list: null,
    value: '',
  },
  'deal.source': {
    item: 'deal.source',
    changeStage: [0, 1, 2],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'sources',
    value: '',
  },
  'stage.type': {
    item: 'stage.type',
    changeStage: [0, 1, 2, 3, 4, 5, 6, 7],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'stageTypes',
    value: '',
  },
  'responsible.id': {
    item: 'responsible.id',
    changeStage: [0, 1, 2, 3, 4, 5, 6, 7],
    type: 'select',
    'min-value': null,
    'max-value': null,
    simbols: null,
    list: 'responsibleIds',
    value: '',
  },
}
